app:
  image: ibmcom/swift-ubuntu:4.0.2
  ports:
    - "8080:8080"
  volumes:
    - .:/FileResolver
  command: bash -c "cd /FileResolver && swift package --build-path .build-ubuntu clean && swift build --build-path .build-ubuntu && swift test"
